In [9]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
arr=np.array([1,2,3])
print(arr)
arr_2d=np.array([[1,2],[3,4]])
print(arr_2d)

[1 2 3]
[1 2 3]
[[1 2]
 [3 4]]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("size:",arr.size)
print("dimension:",arr.ndim)

shape: (2, 3)
size: 6
dimension: 2


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped_arr =arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr =arr.reshape(3,2)
print(reshaped_arr)
reshaped_arr =arr.reshape(-1,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
flattened_arr=arr_2d.flatten()
print(flattened_arr)


[1 2 3 4 5 6]


In [23]:
import numpy as np
arr=int(input("enter the list"))
arr_2=int(input("enter the list"))
print([arr])
print([arr_2])
reshaped_arr=np.array([[arr],[arr_2]])
print(reshaped_arr)
reshaped_arr=np.array([[arr_2],[arr]])
print(reshaped_arr)

enter the list 1
enter the list 2


[1]
[2]
[[1]
 [2]]
[[2]
 [1]]


In [25]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2])
print(arr[1:4])
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1:,:3])

30
[20 30 40]
[[4 5 6]
 [7 8 9]]


In [27]:
import numpy as np
arr=np.arange(0,10,2)
print(arr)
arr=np.linspace(0,1,5)
print(arr)
arr=np.logspace(1,3,4)
print(arr)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  10.           46.41588834  215.443469   1000.        ]


In [29]:
import numpy as np
zeros=np.zeros([2,3])
print(zeros)
ones=np.ones([2,3])
print(ones)
identity=np.eye(4,dtype=int)
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [31]:
import numpy as np
random_floats=np.random.rand(2,3)
print(random_floats)
random_ints=np.random.randint(1,10,(3,3))
print(random_ints)

[[0.10594758 0.57505613 0.34959006]
 [0.64310022 0.05333576 0.18801767]]
[[1 6 1]
 [7 1 3]
 [4 3 9]]


In [36]:
import numpy as np
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter step value: "))
arr = np.arange(start, end, step)
print(arr)
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter number of samples: "))  
arr_1 = np.linspace(start, end, step)
print(arr_1)
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter number of samples: "))  
arr = np.logspace(start, end, step)
print(arr_2)
    

Enter start value:  2
Enter end value:  3
Enter step value:  4


[2]


Enter start value:  5
Enter end value:  6
Enter number of samples:  6


[5.  5.2 5.4 5.6 5.8 6. ]


Enter start value:  1
Enter end value:  2
Enter number of samples:  3


2


In [40]:
import numpy as np
zeros=np.zeros([2,3],"i")
print(zeros)
ones=np.ones([2,3],"i")
print(ones)
identity=np.eye(3,dtype=int)
print(identity)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [46]:
import numpy as np
r=int(input("enter row:"))
c=int(input("enter col:"))
r1=int(input("matrix:"))
c1=int(input("martix2:"))
zeros=np.zeros([r,c],"i")
print(zeros)
random_f=np.random.rand(r,c)
print(random_f)
print(np.random.randint(r,c,(r1,c1)))

enter row: 4
enter col: 4
matrix: 2
martix2: 2


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0.74749315 0.06378046 0.11177759 0.39218753]
 [0.33697206 0.67551423 0.44346424 0.60271998]
 [0.4536931  0.86037894 0.3245691  0.96939242]
 [0.67200796 0.39973163 0.49495508 0.56297528]]


ValueError: low >= high

In [48]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [50]:
import numpy as np
a=np.array(([[1,2],[3,4]]))
b=np.array([[5,6],[7,8]])
result=np.dot(a,b)
print(result)


[[19 22]
 [43 50]]


In [52]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [54]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("minimum:",np.min(arr))
print("maximum:",np.max(arr))
print("mean:",np.mean(arr))

sum: 21
minimum: 1
maximum: 6
mean: 3.5


In [56]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))
print(np.mean(arr,axis=1,dtype=int))


[5 7 9]
[2 5]


In [58]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 1  3  6 10]
[ 1  2  6 24]


In [60]:
import numpy as np
arr=np.array([10,3,7,1])
sorted_arr=np.sort(arr)
print(sorted_arr)
sorted_indices=np.argsort(arr)
print(sorted_indices)

[ 1  3  7 10]
[3 1 2 0]


In [62]:
import numpy as np
arr=np.array([1,2,3,2,2,3,3,3])
unique_elements=np.unique(arr)
print(unique_elements)

[1 2 3]


In [64]:
import numpy as np
arr=np.array([10,15,20,25])
indices=np.where(arr>15)
print(indices)
values=arr[np.where(arr>15)]
print(values)


(array([2, 3], dtype=int64),)
[20 25]


In [66]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.transpose(arr))


[[1 4]
 [2 5]
 [3 6]]


In [68]:
import numpy as np
arr=np.array([[1,2],[3,4]])
det = np.linalg.det(arr)
print(det)
inv=np.linalg.inv(arr)
print(inv)


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [70]:
import numpy as np
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[3,2,1]])
concated=np.concatenate([a,b])
print(concated)


[[1 2 3]
 [7 8 9]
 [4 5 6]
 [3 2 1]]


In [82]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1=np.array([[11,12,13],[14,15,16],[20,21,23]])
split_arr=np.split(arr,3)
print(split_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [1]:
import numpy as np
arr=np.array([[2,7,6],[9,5,1],[4,3,8]])
print("sum:",np.sum(arr))
diagonal=np.diagonal(arr)
print(diagonal)
vstacked=np.vstack([arr])
print(vstacked)
hstacked=np.hstack([arr])
print(hstacked)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.sum(diagonal))


sum: 45
[2 5 8]
[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[2 7 6]
 [9 5 1]
 [4 3 8]]
[15 15 15]
[15 15 15]
15


In [5]:
import numpy as np
a=[]
r=int(input("enter numbers:"))
for i in range(r):
    c=int(input("enter "+str(i+1)+" value:"))
    a.append(c)
arr_2d=np.array(a)
unique_elements=np.unique(arr_2d)
print(unique_elements)
a=np.size(arr_2d)
print(a)
b=np.size(unique_elements)
print(b)
reshaped_arr=arr_2d.reshape(3,3)
print(reshaped_arr)
x=np.sum(reshaped_arr,axis=0)#column
y=np.sum(reshaped_arr,axis=1)
t=np.trace(reshaped_arr)
print(x)
print(y)
if np.unique(x)==np.unique(y)==t:
   print("magic")
else:
   print("not magic")

enter numbers: 9
enter 1 value: 4
enter 2 value: 9
enter 3 value: 2
enter 4 value: 3
enter 5 value: 5
enter 6 value: 7
enter 7 value: 8
enter 8 value: 1
enter 9 value: 6


[1 2 3 4 5 6 7 8 9]
9
9
[[4 9 2]
 [3 5 7]
 [8 1 6]]
[15 15 15]
[15 15 15]
magic


In [15]:
import numpy as np
A=[]
A=list(map(lambda x: x, range(0, 10)))
print(A)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
import numpy as np
arr=np.random.randint(1,20,(3,3))
print(arr)
print("sum:",np.sum(arr,axis=1))



[[ 8 12 10]
 [19  1 11]
 [16  8  2]]
sum: [30 31 26]


In [19]:
import numpy as np
A=[[1,2],[3,4]]
B=[[5,6],[7,8]]
add=np.add(A,B)
print(add)
mul=np.multiply(A,B)
print(mul)
dot=np.dot(A,B)
print(dot)



[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [21]:
import numpy as np
A=[]
B=[]
A=list(map(lambda x: x, range(1, 5)))
B=list(map(lambda x: x, range(6,10)))
add=np.add(A,B)
print(add)
mul=np.multiply(A,B)
print(mul)
dot=np.dot(A,B)
print(dot)


[ 7  9 11 13]
[ 6 14 24 36]
80


In [23]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Matrix Multiplication (using dot):\n", result)
result2 = A @ B
print("Matrix Multiplication (using @):\n", result2)

Matrix Multiplication (using dot):
 [[19 22]
 [43 50]]
Matrix Multiplication (using @):
 [[19 22]
 [43 50]]


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr % 2 == 0
print("Mask for even numbers:", mask)
even_numbers = arr[mask]
print("Even Numbers:", even_numbers)

Mask for even numbers: [False  True False  True False  True]
Even Numbers: [2 4 6]


In [27]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
result = arr[indices]
print("Elements at indices 0, 2, 4:", result)

Elements at indices 0, 2, 4: [10 30 50]


In [29]:
import numpy as np
angles=np.array([0,np.pi/2,np.pi])
sine_values=np.sin(angles)
cosine_values=np.cos(angles)
tangent_values=np.tan(angles)
print("sine_values:",sine_values)
print("cosine_values:",cosine_values)
print("tangent_values:",tangent_values)

sine_values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosine_values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tangent_values: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [31]:
import numpy as np
arcsin_values=np.arcsin(1)
print("arcsin(1):",np.degrees(arcsin_values))

arcsin(1): 90.0


In [33]:
import numpy as np
arr=np.array([1,2,3])
exp_values=np.exp(arr)
print("exponential values:",exp_values)
log_values=np.log(arr)
print("Natural log:",log_values)
log10_values=np.log10(arr)
print("log base 10:",log10_values) 

exponential values: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0.         0.69314718 1.09861229]
log base 10: [0.         0.30103    0.47712125]


In [35]:
import numpy as np
arr=np.array([1.56,2.35,3.89])
rounded=np.round(arr)
print("Rounded values:",rounded)
floored=np.floor(arr)
print("floored values:",floored)
ceiled=np.ceil(arr)
print("ceiled values:",ceiled)

Rounded values: [2. 2. 4.]
floored values: [1. 2. 3.]
ceiled values: [2. 3. 4.]


In [37]:
import numpy as np
data=np.array([1,2,3,4,5])
mean_value=np.mean(data)
print("mean:",mean_value)
median_value=np.median(data)
print("median:",median_value)
variance_value=np.var(data)
print("variance:",variance_value)
std_dev_value=np.std(data)
print("standard deviation:",std_dev_value)


mean: 3.0
median: 3.0
variance: 2.0
standard deviation: 1.4142135623730951


In [39]:
import numpy as np
A=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
B=np.array([8,-11,-3])
x=np.linalg.solve(A,B)
print("solution:",x)

solution: [ 2.  3. -1.]


In [41]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([2,3])
x=np.linalg.solve(A,B)
print("solution:",x)

solution: [-1.   1.5]


In [43]:
import numpy as np
arr=np.array([1,np.nan,3,4])
nan_check=np.isnan(arr)
print("nan check:",nan_check)
arr_cleaned=np.nan_to_num(arr,nan=-1)
print("cleaned array:",arr_cleaned)

nan check: [False  True False False]
cleaned array: [ 1. -1.  3.  4.]


In [47]:
import time
import numpy as np
arr=np.arange(1e6)
print(arr)
start=time.time()
loop_result=[x**2 for x in arr]
end=time.time()
print("loop time:",end-start)
start=time.time()
vectorized_result=arr**2
end=time.time()
print("numpy time:",end-start)

[0.00000e+00 1.00000e+00 2.00000e+00 ... 9.99997e+05 9.99998e+05
 9.99999e+05]
loop time: 0.2843649387359619
numpy time: 0.00958561897277832
